db:
  # url: "sqlite:///./webapp.db"
  url: "postgresql://postgres:postgres@postgres:5432/postgres"

minio:
  endpoint: <YOUT_S3_ENDPOINT>
  access_key: <YOUR_ACCESS_KEY>
  secret_key: <YOUR_SECRET_KEY>
  secure: true
  bucket_name: <YOUT_BUCKET_NAME>