version: "3.7"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: webapp
    depends_on:
      - postgres
    # 마이그레이션 수행 후 컨테이너 종료
    command: alembic upgrade head
    restart: "no"

  webapp:
    image: webapp
    depends_on:
      - postgres
      # migrate 컨테이너가 실행 완료되어야 webapp 실행 (컨테이너가 종료된 상태여도 아래와 같이 depends_on 설정합니다)
      - migrate
    ports:
      - "8000:8000"
    volumes:
      - "./:/code"
    command: uvicorn webapp.application:app --host 0.0.0.0 --port 8000 --reload
