version: "3.7"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  migrate:
    image: webapp
    depends_on:
      - postgres
    # 마이그레이션 수행 후 컨테이너 종료
    command: alembic upgrade head
    restart: "no"
    volumes:
      - "./:/code"
      - "./migrations:/code/migrations"

  webapp:
    depends_on:
      - postgres
      - migrate
    build: ./
    image: webapp
    ports:
      - "8000:8000"
    volumes:
      - "./:/code"
    command: uvicorn webapp.application:app --host 0.0.0.0 --port 8000

volumes:
  postgres_data:
