"""Add ImageObject to user and order

Revision ID: 29c055103f45
Revises: 3241fa6cf17c
Create Date: 2025-04-01 04:40:24.944322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29c055103f45'
down_revision: Union[str, None] = '3241fa6cf17c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.add_column('orders', sa.Column('order_image_list', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.drop_column('orders', 'order_image_path_list')
    op.add_column('users', sa.Column('profile_image', sa.Integer(), nullable=True))
    op.create_foreign_key("fk_users_profile_image", 'users', 'images', ['profile_image'], ['id'])
    op.drop_column('users', 'profile_image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint("fk_users_profile_image", 'users', type_='foreignkey')
    op.drop_column('users', 'profile_image')
    op.add_column('orders', sa.Column('order_image_path_list', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('orders', 'order_image_list')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###
