"""add_quantity_on_order

Revision ID: 48a2f446fd91
Revises: adbae0db08b1
Create Date: 2025-02-17 14:28:53.013026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48a2f446fd91'
down_revision: Union[str, None] = 'adbae0db08b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. nullable한 컬럼으로 먼저 추가
    op.add_column('orders', sa.Column('quantity', sa.String(), nullable=True))
    
    # 2. 기존 데이터 업데이트
    op.execute("UPDATE orders SET quantity = '0'")
    
    # 3. NOT NULL 제약조건 추가
    op.alter_column('orders', 'quantity',
                    existing_type=sa.String(),
                    nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'quantity')
    # ### end Alembic commands ###
