"""Replace image-url-list to image-path-list

Revision ID: 3241fa6cf17c
Revises: fd4a7a6155c2
Create Date: 2025-03-07 04:02:03.779338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3241fa6cf17c'
down_revision: Union[str, None] = 'fd4a7a6155c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_image_path_list', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('orders', 'order_image_url_list')
    op.add_column('users', sa.Column('profile_image_path', sa.String(), nullable=True))
    op.drop_column('users', 'profile_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'profile_image_path')
    op.add_column('orders', sa.Column('order_image_url_list', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('orders', 'order_image_path_list')
    # ### end Alembic commands ###
