"""Add image-url-list

Revision ID: fd4a7a6155c2
Revises: 5f848f9e2147
Create Date: 2025-03-07 02:46:31.423861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd4a7a6155c2'
down_revision: Union[str, None] = '5f848f9e2147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_image_url_list', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('orders', 'order_image_path_list')
    op.add_column('users', sa.Column('profile_image_url', sa.String(), nullable=True))
    op.drop_column('users', 'profile_image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'profile_image_url')
    op.add_column('orders', sa.Column('order_image_path_list', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('orders', 'order_image_url_list')
    # ### end Alembic commands ###
